import { User } from '.';
import { Cart } from './cart';
import { Channel } from './channel';
import { Currency } from './currency';
import { Transaction } from './transaction';

export type Order = {
    id: number;
    user_id?: number;
    channel_id: number;
    status: string;
    refference?: string;
    customer_refference?: string;
    sub_total: number;
    discount_total: number;
    shipping_total: number;
    tax_breakdown: string;
    tax_total: number;
    total: number;
    notes?: string;
    currency_code: string;
    compare_currency_code?: string;
    exchange_rate: number;
    placed_at?: string;
    meta?: string;
    customer_id?: number;
    new_customer: boolean;
    discount_breakdown?: string;
    shipping_breakdown?: string;
    cart_id?: number;
    fingerprint?: string;
    channel?: Channel;
    cart?: Cart;
    lines?: OrderLine[];
    physical_lines?: OrderLine[];
    digital_lines?: OrderLine[];
    product_lines?: OrderLine[];
    currency?: Currency;
    addresses?: OrderAddress[];
    shipping_address?: OrderAddress;
    billing_address?: OrderAddress;
    transactions?: Transaction[];
    captures?: Transaction[];
    intents?: Transaction[];
    refunds?: Transaction[];
    user?: User;
};

export type OrderLine = {
    id: number;
    order_id: number;
    purchasable_type: string;
    purchasable_id: number;
    type: string;
    description: string;
    option?: string;
    identifier: string;
    unit_price: number;
    unit_quantity: number;
    quantity: number;
    sub_total: number;
    discount_total: number;
    tax_breakdown: string;
    tax_total: number;
    total: number;
    notes?: string;
    meta?: string;
};

export type OrderAddress = {
    id: number;
    order_id?: number;
    country_id?: number;
    title?: string;
    first_name: string;
    last_name: string;
    company_name?: string;
    line_one: string;
    line_two?: string;
    line_three?: string;
    city: string;
    state?: string;
    postcode: string;
    delivery_instructions?: string;
    contact_email?: string;
    contact_phone?: string;
    type: string;
    shipping_option?: string;
    meta?: string;
    country?: Country;
};
